### ISSUE TITLE
✨ Adopt `ccache` for faster CI builds

### ISSUE THREAD

**Issue by burgholzer** [cda-tum/mqt-qmap#253]
### What's the problem this feature will solve?

CI builds can be quite slow and take up a considerable amount of time.
`ccache`, in particular https://github.com/hendrikmuhs/ccache-action allows to set up a consistent compiler cache for your GitHub CI workflows that speeds up compilation across runs.

### Describe the solution you'd like

Adopt `ccache` for our CI builds. Should be as simple as
```yaml
- name: Setup ccache
  uses: hendrikmuhs/ccache-action@v1.2
  with:
    key: '${{matrix.os}}-${{matrix.compiler}}-${{matrix.build_type}}'
    variant: ccache
    save: true
    max-size: 10G
```
and passing `-D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache` to CMake.

Some slight modification might be necessary for Windows.

Reference PR: 
- https://github.com/cda-tum/qfr/pull/323
